source:
  repository: https://github.com/shortrib-net/outsystems-image
  branch: feature-automation

template:
  vm_name: "outsystems-image"
  numvcpus: "2"
  memsize: "4096"
  disk_size: "102400"

image:
  url: "https://software-download.microsoft.com/download/pr/17763.737.190906-2324.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us_1.iso"
  checksum: "3022424f777b66a698047ba1c37812026b9714c5"

